<?php
// 
$settings = array(
	'LANGUAGE' => 'en',

	'BACKGROUND_COLOR' => '#18337C',

	'PATH_DOT_COLOR' => '#00ff00',
	'PATH_INTERSECT_DOT_COLOR' => '#000000',

	'MAX_START_FORCE_COLOR' => '#ffffff',

	'PEPES_COSMOLOGICAL_CONSTANT' => 5.5,

	'DEFAULT_PLANET_MASS' => 50000,
	'DEFAULT_PLANET_RADIUS' => 30.0,

	'MIN_MASS' => 0,
	'MAX_MASS' => 99999,
	'SLIDER_STEP_MASS' => 500,

	'MIN_BOUNCE' => 0.0,
	'MAX_BOUNCE' => 1.0,
	'SLIDER_STEP_BOUNCE' => 0.1,

	'PATH_MAX_NUM_POINTS' => 65535,


	null
);
?>